# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/owen/dev/GRAAI

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/owen/dev/GRAAI

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/owen/dev/GRAAI/CMakeFiles /home/owen/dev/GRAAI/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/owen/dev/GRAAI/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GRAAI

# Build rule for target.
GRAAI: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GRAAI
.PHONY : GRAAI

# fast build rule for target.
GRAAI/fast:
	$(MAKE) -f CMakeFiles/GRAAI.dir/build.make CMakeFiles/GRAAI.dir/build
.PHONY : GRAAI/fast

src/GRAAI.o: src/GRAAI.cc.o

.PHONY : src/GRAAI.o

# target to build an object file
src/GRAAI.cc.o:
	$(MAKE) -f CMakeFiles/GRAAI.dir/build.make CMakeFiles/GRAAI.dir/src/GRAAI.cc.o
.PHONY : src/GRAAI.cc.o

src/GRAAI.i: src/GRAAI.cc.i

.PHONY : src/GRAAI.i

# target to preprocess a source file
src/GRAAI.cc.i:
	$(MAKE) -f CMakeFiles/GRAAI.dir/build.make CMakeFiles/GRAAI.dir/src/GRAAI.cc.i
.PHONY : src/GRAAI.cc.i

src/GRAAI.s: src/GRAAI.cc.s

.PHONY : src/GRAAI.s

# target to generate assembly for a file
src/GRAAI.cc.s:
	$(MAKE) -f CMakeFiles/GRAAI.dir/build.make CMakeFiles/GRAAI.dir/src/GRAAI.cc.s
.PHONY : src/GRAAI.cc.s

src/ModbusPkg.o: src/ModbusPkg.cc.o

.PHONY : src/ModbusPkg.o

# target to build an object file
src/ModbusPkg.cc.o:
	$(MAKE) -f CMakeFiles/GRAAI.dir/build.make CMakeFiles/GRAAI.dir/src/ModbusPkg.cc.o
.PHONY : src/ModbusPkg.cc.o

src/ModbusPkg.i: src/ModbusPkg.cc.i

.PHONY : src/ModbusPkg.i

# target to preprocess a source file
src/ModbusPkg.cc.i:
	$(MAKE) -f CMakeFiles/GRAAI.dir/build.make CMakeFiles/GRAAI.dir/src/ModbusPkg.cc.i
.PHONY : src/ModbusPkg.cc.i

src/ModbusPkg.s: src/ModbusPkg.cc.s

.PHONY : src/ModbusPkg.s

# target to generate assembly for a file
src/ModbusPkg.cc.s:
	$(MAKE) -f CMakeFiles/GRAAI.dir/build.make CMakeFiles/GRAAI.dir/src/ModbusPkg.cc.s
.PHONY : src/ModbusPkg.cc.s

src/ModbusServer.o: src/ModbusServer.cc.o

.PHONY : src/ModbusServer.o

# target to build an object file
src/ModbusServer.cc.o:
	$(MAKE) -f CMakeFiles/GRAAI.dir/build.make CMakeFiles/GRAAI.dir/src/ModbusServer.cc.o
.PHONY : src/ModbusServer.cc.o

src/ModbusServer.i: src/ModbusServer.cc.i

.PHONY : src/ModbusServer.i

# target to preprocess a source file
src/ModbusServer.cc.i:
	$(MAKE) -f CMakeFiles/GRAAI.dir/build.make CMakeFiles/GRAAI.dir/src/ModbusServer.cc.i
.PHONY : src/ModbusServer.cc.i

src/ModbusServer.s: src/ModbusServer.cc.s

.PHONY : src/ModbusServer.s

# target to generate assembly for a file
src/ModbusServer.cc.s:
	$(MAKE) -f CMakeFiles/GRAAI.dir/build.make CMakeFiles/GRAAI.dir/src/ModbusServer.cc.s
.PHONY : src/ModbusServer.cc.s

src/TagEngine.o: src/TagEngine.cc.o

.PHONY : src/TagEngine.o

# target to build an object file
src/TagEngine.cc.o:
	$(MAKE) -f CMakeFiles/GRAAI.dir/build.make CMakeFiles/GRAAI.dir/src/TagEngine.cc.o
.PHONY : src/TagEngine.cc.o

src/TagEngine.i: src/TagEngine.cc.i

.PHONY : src/TagEngine.i

# target to preprocess a source file
src/TagEngine.cc.i:
	$(MAKE) -f CMakeFiles/GRAAI.dir/build.make CMakeFiles/GRAAI.dir/src/TagEngine.cc.i
.PHONY : src/TagEngine.cc.i

src/TagEngine.s: src/TagEngine.cc.s

.PHONY : src/TagEngine.s

# target to generate assembly for a file
src/TagEngine.cc.s:
	$(MAKE) -f CMakeFiles/GRAAI.dir/build.make CMakeFiles/GRAAI.dir/src/TagEngine.cc.s
.PHONY : src/TagEngine.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... GRAAI"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... src/GRAAI.o"
	@echo "... src/GRAAI.i"
	@echo "... src/GRAAI.s"
	@echo "... src/ModbusPkg.o"
	@echo "... src/ModbusPkg.i"
	@echo "... src/ModbusPkg.s"
	@echo "... src/ModbusServer.o"
	@echo "... src/ModbusServer.i"
	@echo "... src/ModbusServer.s"
	@echo "... src/TagEngine.o"
	@echo "... src/TagEngine.i"
	@echo "... src/TagEngine.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

